# These are supported funding model platforms


patreon: isaevdimka
custom: ["https://www.paypal.me/octocat", "ton://transfer/EQApG6ILPC2-4UeUXth6XLi9zGMzWNQQpBedpOMk7pzcNKEy", "https://www.tinkoff.ru/rm/isaev.dmitriy74/aBdAl72183"]
